### PR TITLE
setup.py

### PR DESCRIPTION
**Pull request by GabrielWen**

### CODE REVIEW

**Comment by GabrielWen** [comment]
It works fine on new-made Amazon instance.  I don't understand why it fails here...

**Comment by fegin** [comment]
You can check if this is caused by incorrect commands in .travis.yml.

**Comment by GabrielWen** [comment]
Tested using stale version of Ubuntu(12.04), it did behaves as Travis did.  But I don't understand the connection between system version and the error.

Error msg that crashes makefile looks like this:
c++ -o /home/travis/build/spartan-array/spartan/spartan/src/obj/pkg/worker /home/travis/build/spartan-array/spartan/spartan/src/core/worker.o -L/home/travis/build/spartan-array/spartan/spartan/src/rpc/simple-rpc/build -L/home/travis/build/spartan-array/spartan/spartan/src/obj/lib -L/home/travis/build/spartan-array/spartan/spartan/src/obj/rpc -L/home/travis/build/spartan-array/spartan/spartan/src -L/home/travis/build/spartan-array/spartan/spartan/src/rpc/simple-rpc -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -lbase -lpython2.7 -std=c++11 -lsimplerpc -lspartan_array -lcore -Wl,-rpath='$ORIGIN/lib'
/home/travis/build/spartan-array/spartan/spartan/src/obj/lib/libspartan_array.so: undefined reference to `CArray::CArray(long*, int, char, char*, PyArrayObject*)'
collect2: ld returned 1 exit status

**Comment by GabrielWen** [comment]
It appears to be flag problem, I'll update it after I figure out which one caused the problem.

**Comment by GabrielWen** [comment]
Current version ran fine on new instance of EC2 with same environment as Travis.  I'm checking whether it's problem of commands in travis.yml

**Comment by GabrielWen** [comment]
Compiled version: /home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/numpy/version.pyc 1.9.1

Runtime version: /usr/lib/python2.7/dist-packages/numpy/version.pyc 1.6.1

It appears that Travis will fetch newer version of numpy in local dir when compilation, whereas fetch older version of numpy in global dir when runtime.

**Comment by GabrielWen** [comment]
It looks like when Cython is installing, numpy >= 1.7 is a requirement and somehow install it into local library.  I'll have to find a way to force this lookup into local librayr instead of global one.

Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7 in /home/travis/virtualenv/python2.7_with_system_site_packages/lib/python2.7/site-

**Comment by fegin** [comment]
Another way is to check if we can use newer version of ubuntu for Travis.
12.04 will soon expire the support date.

**Comment by GabrielWen** [comment]
Looks like it's still working on progress.
https://github.com/travis-ci/travis-ci/issues/2046

**Pull request merged**
